name: Build and Push Docker Images

on:
  push:
    paths:
      - templates/**/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PKR_VAR_registry: ghcr.io
      PKR_VAR_registry_username: ${{ github.actor }}
      PKR_VAR_registry_password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize Packer
        run: packer init .

      - name: Validate Packer configurations
        run: packer validate .

      - name: Packer build
        run: packer build .
